"""Render Postfix templates in the built image, then validate with postfix check.

These are config templates (not code), so this is a 'render then assert' test:
run render-config inside the image with representative env, then grep the output
and run `postfix check`. No Postgres/Dovecot/Rspamd daemons are required —
postfix check only validates config syntax and referenced files.
"""
import os
import shutil
import subprocess
import textwrap

import pytest
from conftest import MAIL_HOST, SMTP_PORT, SUBMISSION_PORT, SMTPS_PORT

IMAGE = "mail-server:test"

# Representative env covering every token render-config substitutes into the
# Postfix templates (postfix-pgsql maps + main.cf).
ENV = {
    "MAIL_HOSTNAME": "mail.example.test",
    "MESSAGE_SIZE_LIMIT": "52428800",
    "TLS_CERT_FILE": "/tls/fullchain.pem",
    "TLS_KEY_FILE": "/tls/privkey.pem",
    "RELAYHOST": "",
    "POSTSCREEN_ENABLED": "true",
    "PG_HOST": "db",
    "PG_PORT": "5432",
    "PG_DBNAME": "mail",
    "PG_USER": "mail_ro",
    "PG_PASSWORD": "s3cret",
    "REDIS_HOST": "redis",
}


def _run_in_image(script):
    """Run a /bin/sh script inside a fresh container, return CompletedProcess."""
    env_args = []
    for k, v in ENV.items():
        env_args += ["-e", f"{k}={v}"]
    cmd = ["docker", "run", "--rm", "--entrypoint", "/bin/sh", *env_args, IMAGE, "-c", script]
    return subprocess.run(cmd, capture_output=True, text=True)


def test_render_then_postfix_check_passes():
    # render-config writes /etc/postfix/{main.cf,master.cf} + /etc/postfix/sql/*.cf.
    # A self-signed cert is generated by render-config when TLS files are absent.
    script = textwrap.dedent(
        """
        set -e
        /usr/local/bin/render-config.sh
        echo '=== main.cf ==='
        postconf -n >/dev/null
        echo '=== postfix check ==='
        postfix check
        echo 'CHECK_OK'
        """
    )
    r = _run_in_image(script)
    assert r.returncode == 0, f"stdout:\n{r.stdout}\nstderr:\n{r.stderr}"
    assert "CHECK_OK" in r.stdout, r.stdout


def test_pgsql_maps_substituted_no_leftover_tokens():
    script = textwrap.dedent(
        """
        set -e
        /usr/local/bin/render-config.sh
        # No unresolved ${...} tokens may remain in the rendered Postfix configs.
        if grep -RnE '\\$\\{[A-Za-z_]+\\}' /etc/postfix/main.cf /etc/postfix/master.cf /etc/postfix/sql/ ; then
            echo 'LEFTOVER_TOKENS'
            exit 1
        fi
        # PG connection landed in the maps.
        grep -q 'hosts = db:5432' /etc/postfix/sql/virtual_mailbox_maps.cf
        grep -q 'user = mail_ro' /etc/postfix/sql/sender_login_maps.cf
        echo 'SUBST_OK'
        """
    )
    r = _run_in_image(script)
    assert r.returncode == 0, f"stdout:\n{r.stdout}\nstderr:\n{r.stderr}"
    assert "SUBST_OK" in r.stdout, r.stdout


def test_main_cf_wiring():
    """Key main.cf directives the rest of the stack depends on."""
    script = textwrap.dedent(
        """
        set -e
        /usr/local/bin/render-config.sh
        postconf myhostname | grep -q 'myhostname = mail.example.test'
        postconf smtpd_sasl_type | grep -q 'smtpd_sasl_type = dovecot'
        postconf smtpd_sasl_path | grep -q 'smtpd_sasl_path = private/auth'
        postconf virtual_transport | grep -q 'virtual_transport = lmtp:unix:private/dovecot-lmtp'
        postconf smtpd_milters | grep -q 'inet:localhost:11332'
        postconf non_smtpd_milters | grep -q 'inet:localhost:11332'
        postconf smtp_line_length_limit | grep -q 'smtp_line_length_limit = 0'
        postconf message_size_limit | grep -q 'message_size_limit = 52428800'
        # Global SASL must be OFF (only 587/465 re-enable it).
        postconf smtpd_sasl_auth_enable | grep -q 'smtpd_sasl_auth_enable = no'
        echo 'WIRING_OK'
        """
    )
    r = _run_in_image(script)
    assert r.returncode == 0, f"stdout:\n{r.stdout}\nstderr:\n{r.stderr}"
    assert "WIRING_OK" in r.stdout, r.stdout


# Host/ports where compose.test.yml (phase A) publishes the mail-server image.
# Use env-var overrides first, then fall back to conftest constants.
MAIL_HOST = os.environ.get("MAIL_TEST_HOST", MAIL_HOST)
PORT_SMTP = int(os.environ.get("MAIL_TEST_PORT_25", SMTP_PORT))
PORT_SUBMISSION = int(os.environ.get("MAIL_TEST_PORT_587", SUBMISSION_PORT))
PORT_SMTPS = int(os.environ.get("MAIL_TEST_PORT_465", SMTPS_PORT))

_have_swaks = shutil.which("swaks") is not None


def _ehlo_capabilities(port, tls):
    """Return swaks EHLO transcript for a port (tls: '', 'starttls', 'wrap')."""
    cmd = [
        "swaks", "--server", f"{MAIL_HOST}:{port}",
        "--ehlo", "probe.example.test",
        "--quit-after", "EHLO",
        "--hide-send", "--timeout", "20",
    ]
    if tls == "starttls":
        cmd += ["--tls"]
    elif tls == "wrap":
        cmd += ["--tlsc"]  # implicit/wrapper TLS for :465
    r = subprocess.run(cmd, capture_output=True, text=True)
    return r.stdout + r.stderr


@pytest.mark.integration
@pytest.mark.skipif(not _have_swaks, reason="swaks not installed")
def test_submission_ports_tls_and_no_auth_on_mx(compose):
    """Phase E guarantees: the MX port (:25) never advertises AUTH, and the
    submission ports (:587 STARTTLS, :465 implicit TLS) are up and TLS-capable.

    AUTH is gated behind TLS (smtpd_tls_auth_only) *and* requires the Dovecot
    SASL backend (smtpd_sasl_type=dovecot -> private/auth), which is wired in
    phase F. Until then, smtpd on 587/465 fatals with "no SASL authentication
    mechanisms" as soon as a TLS submission session needs AUTH, so the post-TLS
    conversation cannot be exercised here. The end-to-end "AUTH is advertised and
    a real login succeeds on 587/465" guarantee is verified by the phase F
    submission test (F.9, test_dovecot_*). At phase E we assert only the
    invariants that hold without a SASL backend: no AUTH on the MX, STARTTLS
    offered on 587, and a working implicit-TLS handshake on 465.
    """
    # :25 must NOT advertise AUTH (no SASL on the public MX port) — true now and
    # forever, independent of the SASL backend.
    cap25 = _ehlo_capabilities(PORT_SMTP, tls="")
    assert "AUTH" not in cap25.upper().replace("AUTHENTICATION", ""), (
        f"AUTH unexpectedly advertised on :25\n{cap25}"
    )
    # :587 must offer STARTTLS (the encrypted submission entrypoint).
    cap587 = _ehlo_capabilities(PORT_SUBMISSION, tls="")
    assert "STARTTLS" in cap587.upper(), f"STARTTLS not offered on :587\n{cap587}"
    # :465 must establish implicit/wrapper TLS (cipher negotiated). The banner
    # that follows needs the SASL backend (phase F), so we assert the handshake.
    cap465 = _ehlo_capabilities(PORT_SMTPS, tls="wrap")
    assert "tls started" in cap465.lower(), (
        f":465 did not establish implicit/wrapper TLS\n{cap465}"
    )
