# DMARC verification (always on; emits Authentication-Results + drives
# quarantine/reject via policy).  Aggregate (RUA) reporting is gated by
# DMARC_REPORT_ENABLED; Rspamd has no forensic (RUF) support.  Reports are
# generated by the dmarc-report s6 timer running `rspamadm dmarc_report`, not
# auto-sent by the daemon, so this block only configures the sender identity
# and the Redis-backed report store.
reporting {
  enabled = ${DMARC_REPORT_ENABLED};
  email = "${DMARC_REPORT_EMAIL}";
  domain = "${MAIL_HOSTNAME}";
  org_name = "${MAIL_HOSTNAME}";
  from_name = "${MAIL_HOSTNAME}";
  msgid_from = "dmarc";
}
